project_id = "qrermcbuxylxwbimdmkt"

[functions.google-oauth-start]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.microsoft-oauth-start]
verify_jwt = false

[functions.microsoft-oauth-callback]
verify_jwt = false

[functions.calendar-events]
verify_jwt = false
